vector <- c(1, 0, 2, 3, 6, 8, 12, 15, 0, NA, NA, 9, 4, 16, 2, 0)

print(vector[1])
print(vector[length(vector)])
print(vector[3:5])
print(vector[vector == 2])
print(vector[vector > 4])
print(vector[vector %% 3 == 0])
print(vector[(vector > 4) & (vector %% 3 == 0)])
print(vector[(vector < 1) | (vector > 5)])
print(vector[vector == 0])
print(vector[(vector >= 2) & (vector <= 8)])
